name: Run Files Sequentially on Windows

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  schedule:
    - cron: "0 * * * *" # Runs every hour

jobs:
  run-files:
    runs-on: windows-latest # Use a Windows runner

    steps:

      - name: Download Google Chrome installer 
        run: |
           $installerPath = "$env:TEMP\chrome_installer.exe" 
           Invoke-WebRequest -Uri "https://dl.google.com/chrome/install/latest/chrome_installer.exe" -OutFile $installerPath 
      
      - name: Install Google Chrome
        run: |
           Start-Process -FilePath "$env:TEMP\chrome_installer.exe" -ArgumentList "/silent /install" -Wait 

      - name: Get Chrome Version and install ChromeDriver
        run: |
          echo "Attempting to download ChromeDriver from: $driver_url"
          $driver_url = "https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.205/win64/chromedriver-win64.zip"
          Invoke-WebRequest -Uri $driver_url -OutFile chromedriver-win64.zip
          Expand-Archive -Path chromedriver-win64.zip -DestinationPath C:\chromedriver
          [System.Environment]::SetEnvironmentVariable('PATH', $env:PATH + ';C:\chromedriver', [System.EnvironmentVariableTarget]::Machine)


