name: Run Files Sequentially on Windows

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  schedule:
    - cron: "0 * * * *" # Runs every hour

jobs:
  run-files:
    runs-on: windows-latest # Use a Windows runner

    steps:
      # Step 1: Print environment details
      - name: Print Environment Variables
        run: |
          echo ImageOS: ${{ runner.os }}
          echo Version Details:
          systeminfo

      # Step 2: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Download Google Chrome installer 
        run: |
           $installerPath = "$env:TEMP\chrome_installer.exe" 
           Invoke-WebRequest -Uri "https://dl.google.com/chrome/install/latest/chrome_installer.exe" -OutFile $installerPath 
      
      - name: Install Google Chrome
        run: |
           Start-Process -FilePath "$env:TEMP\chrome_installer.exe" -ArgumentList "/silent /install" -Wait 

      # Step 7: Install ChromeDriver
      - name: Install ChromeDriver
        run: |
          $chrome_version = wmic datafile where name="C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe" get Version /value
          echo "Installed Chrome version: $chrome_version"

          Invoke-WebRequest -Uri "https://storage.googleapis.com/chrome-for-testing-public/$driver_version/win64/chrome-win64.zip" -OutFile chrome-win64.zip
          Expand-Archive -Path chrome-win64.zip -DestinationPath C:\chromedriver
          [System.Environment]::SetEnvironmentVariable('PATH', $env:PATH + ';C:\chromedriver', [System.EnvironmentVariableTarget]::Machine)

      # Step 8: Verify ChromeDriver installation
      - name: Verify ChromeDriver installation
        run: |
          chromedriver --version
          "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --version

