name: Run Files Sequentially

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  schedule:
    - cron: "0 * * * *" # Runs every 1 hour

jobs:
  run-files:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # Specify your Python version, e.g., '3.9'

    # Step 3: Install required Python libraries
    - name: Install Python libraries
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        pip install requests

    # Step 4: Install Google Chrome
    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip curl libx11-dev libx11-xcb1 libxcomposite1 libxrandr2 libgbm1 libasound2

        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get install -y -f

        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        echo "Installed Chrome version: $CHROME_VERSION"

    # Step 5: Install ChromeDriver
    - name: Install ChromeDriver
      run: |
        CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
        wget "https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip" -O chromedriver_linux64.zip

        unzip chromedriver_linux64.zip -d chromedriver
        sudo mv chromedriver/chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

    # Step 6: Verify ChromeDriver installation
    - name: Verify ChromeDriver installation
      run: |
        chromedriver --version
        google-chrome --version

    # Step 7: Run the first script
    - name: Extract port number for BG TV
      run: |
        echo "Running first file..."
        python get_bg_portnum.py

    # Step 8: Wait for a brief pause
    - name: Wait briefly
      run: sleep 60 # Pause for 1 minute

    # Step 9: Run the second script
    - name: Extract tokens for BG TV and renew playlist
      run: |
        echo "Running second file..."
        python make_playlist.py

    # Step 10: Commit and push changes
    - name: Configure Git
      run: |
        git config --global user.name "IPTVSolutions"
        git config --global user.email "mmmw@abv.bg"

    - name: Commit changes
      run: |
        git add .
        git commit -m "Automated update: Ran scripts and updated files" || echo "No changes to commit"

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push
